### ISSUE TITLE
Ramsey uuid namespace is changedRamsey

### ISSUE THREAD

**Issue by mikk150** [p2made/yii2-uuid#1]
If you havent't noticed Ramsey uuid namespace is gone

**Comment by mikk150** [comment]
misunderstangin, something has been messed up in composer :)

**Comment by mikk150** [comment]
no, there is somethind defenitely wrong here

**Comment by p2made** [comment]
I've had a little while off programming.

Fixed this with v3.0.0.

**Comment by mikk150** [comment]
reopen, still many applications I have written are complaining about missing namespace. Your v3 tag points to wrong commit I believe
